import React, { useState, useRef, useEffect } from 'react';
import * as Tone from 'tone';
import { Upload, Play, Pause, Download, Music, RefreshCw, Volume2 } from 'lucide-react';
import { clsx } from 'clsx';
import { twMerge } from 'tailwind-merge';

function cn(...inputs) {
  return twMerge(clsx(inputs));
}

const Footer = () => (
  <footer className="mt-12 text-center text-white/40 text-sm z-10 p-4">
      <p className="italic mb-1">But God made the earth by his power; he founded the world by his wisdom and stretched out the heavens by his understanding. Jeremiah 10:12</p>
      <p className="text-xs mb-1 mt-2">「耶和華用能力創造大地，用智慧建立世界，用聰明鋪張穹蒼。」 耶利米書 10:12</p>
      <p className="text-xs mt-2 pt-2 border-t border-white/10">@ 2025 Generated by Gemini 3.0 Prepared by SF Lau</p>
  </footer>
);

const VisitCounter = () => {
  const [visits, setVisits] = React.useState(0);
  React.useEffect(() => {
    const key = window.location.pathname.replace(/\//g, '_') || 'home';
    // Using a namespace to ensure specific app tracking if needed, or just path-based
    fetch(`https://api.countapi.xyz/hit/keithsflau-profile/${key}`)
      .then(res => res.json())
      .then(data => setVisits(data.value))
      .catch(err => console.error(err));
  }, []);
  return (
    <div className="fixed bottom-2 right-2 text-[10px] text-white/20 pointer-events-none z-50">
      Visits: {visits}
    </div>
  );
};

export default function App() {
  const [file, setFile] = useState(null);
  const [isPlaying, setIsPlaying] = useState(false);
  const [pitch, setPitch] = useState(0); // Semitones
  const [isReady, setIsReady] = useState(false);
  const [duration, setDuration] = useState(0);
  const [currentTime, setCurrentTime] = useState(0);
  const [isProcessing, setIsProcessing] = useState(false);
  const [volume, setVolume] = useState(0);

  const playerRef = useRef(null);
  const pitchShiftRef = useRef(null);
  const audioBufferRef = useRef(null);
  const rafRef = useRef(null);

  // Initialize Tone.js components
  useEffect(() => {
    return () => {
      if (playerRef.current) playerRef.current.dispose();
      if (pitchShiftRef.current) pitchShiftRef.current.dispose();
    };
  }, []);

  const handleFileChange = async (e) => {
    const selectedFile = e.target.files?.[0];
    if (selectedFile) {
      loadFile(selectedFile);
    }
  };

  const loadFile = async (file) => {
    setIsReady(false);
    setFile(file);
    
    // Create URL for the file
    const url = URL.createObjectURL(file);
    
    // Load into Tone.Buffer
    const buffer = await new Tone.Buffer(url);
    audioBufferRef.current = buffer;
    setDuration(buffer.duration);

    // Setup Audio Graph
    if (playerRef.current) playerRef.current.dispose();
    if (pitchShiftRef.current) pitchShiftRef.current.dispose();

    playerRef.current = new Tone.Player(buffer).toDestination();
    pitchShiftRef.current = new Tone.PitchShift(pitch).toDestination();
    
    // Connect: Player -> PitchShift -> Destination
    playerRef.current.disconnect();
    playerRef.current.connect(pitchShiftRef.current);
    
    playerRef.current.sync().start(0);
    
    setIsReady(true);
  };

  // Update Pitch when slider changes
  useEffect(() => {
    if (pitchShiftRef.current) {
      pitchShiftRef.current.pitch = pitch;
    }
  }, [pitch]);

  // Update Volume
  useEffect(() => {
    if (playerRef.current) {
      playerRef.current.volume.value = volume;
    }
  }, [volume]);

  // Play/Pause Logic
  const togglePlay = async () => {
    await Tone.start();
    
    if (isPlaying) {
      Tone.Transport.pause();
    } else {
      Tone.Transport.start();
    }
    setIsPlaying(!isPlaying);
  };

  // Progress Loop
  useEffect(() => {
    const loop = () => {
      if (Tone.Transport.state === 'started') {
        setCurrentTime(Tone.Transport.seconds);
      }
      rafRef.current = requestAnimationFrame(loop);
    };
    loop();
    return () => cancelAnimationFrame(rafRef.current);
  }, []);
  
  // Handle Seek
  const handleSeek = (e) => {
    const time = parseFloat(e.target.value);
    setCurrentTime(time);
    Tone.Transport.seconds = time;
  };

  // Offline Rendering for Download
  const handleDownload = async () => {
    if (!audioBufferRef.current) return;
    
    setIsProcessing(true);
    
    try {
      // Render Offline
      const renderedBuffer = await Tone.Offline(({ transport }) => {
          const player = new Tone.Player(audioBufferRef.current);
          const pitchEffect = new Tone.PitchShift(pitch);
          
          player.connect(pitchEffect);
          pitchEffect.toDestination();
          
          player.sync().start(0);
          transport.start();
      }, audioBufferRef.current.duration);

      // Convert to WAV
      const wavData = toWav(renderedBuffer);
      const blob = new Blob([wavData], { type: 'audio/wav' });
      const url = URL.createObjectURL(blob);
      
      // Trigger Download
      const anchor = document.createElement('a');
      anchor.href = url;
      anchor.download = `transposed_${file.name.replace(/\.[^/.]+$/, "")}.wav`;
      anchor.click();
      
    } catch (err) {
      console.error(err);
      alert("Error processing audio");
    } finally {
      setIsProcessing(false);
    }
  };

  // WAV Converter Helper (Tone.js doesn't export AudioBuffer to WAV natively easily without helpers)
  // Simple Float32 to 16-bit PCM WAV converter
  const toWav = (buffer) => {
      const numOfChan = buffer.numberOfChannels;
      const length = buffer.length * numOfChan * 2 + 44;
      const out = new ArrayBuffer(length);
      const view = new DataView(out);
      const channels = [];
      let sample;
      let offset = 0;
      let pos = 0;

      // write WAVE header
      setUint32(0x46464952);                         // "RIFF"
      setUint32(length - 8);                         // file length - 8
      setUint32(0x45564157);                         // "WAVE"

      setUint32(0x20746d66);                         // "fmt " chunk
      setUint32(16);                                 // length = 16
      setUint16(1);                                  // PCM (uncompressed)
      setUint16(numOfChan);
      setUint32(buffer.sampleRate);
      setUint32(buffer.sampleRate * 2 * numOfChan);  // avg. bytes/sec
      setUint16(numOfChan * 2);                      // block-align
      setUint16(16);                                 // 16-bit (hardcoded in this parser)

      setUint32(0x61746164);                         // "data" - chunk
      setUint32(length - pos - 4);                   // chunk length

      // write interleaved data
      for(let i = 0; i < buffer.numberOfChannels; i++)
        channels.push(buffer.getChannelData(i));

      while(pos < buffer.length) {
        for(let i = 0; i < numOfChan; i++) {             // interleave channels
          sample = Math.max(-1, Math.min(1, channels[i][pos])); // clamp
          sample = (sample < 0 ? sample * 0x8000 : sample * 0x7FFF) | 0; // scale to 16-bit signed int
          view.setInt16(44 + offset, sample, true);          // write 16-bit sample
          offset += 2;
        }
        pos++;
      }

      // buffer helper
      function setUint16(data) {
        view.setUint16(pos, data, true);
        pos += 2;
      }

      function setUint32(data) {
        view.setUint32(pos, data, true);
        pos += 4;
      }
      
      return out;
  };

  return (
    <div className="min-h-screen bg-black text-white flex flex-col items-center justify-center p-6 relative overflow-hidden">
      {/* Background Visuals */}
      <div className="absolute top-[-20%] left-[-20%] w-[600px] h-[600px] bg-purple-900/30 rounded-full blur-[120px]" />
      <div className="absolute bottom-[-20%] right-[-20%] w-[600px] h-[600px] bg-blue-900/20 rounded-full blur-[120px]" />

      <div className="w-full max-w-md z-10">
        <header className="mb-8 text-center">
             <div className="inline-flex items-center justify-center p-3 mb-4 rounded-2xl bg-gradient-to-br from-purple-500/20 to-blue-500/20 border border-white/10 glass shadow-2xl">
                 <Music className="w-8 h-8 text-purple-400" />
             </div>
             <h1 className="text-4xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-purple-400 to-blue-400 mb-2">
               SonicTransposer
             </h1>
             <p className="text-white/50">Details Music Engineering</p>
        </header>

        <div className="glass-card rounded-3xl p-8 space-y-8">
            
            {/* File Upload / Display */}
            {!file ? (
                <div className="relative group cursor-pointer">
                    <input 
                        type="file" 
                        accept="audio/*"
                        onChange={handleFileChange}
                        className="absolute inset-0 w-full h-full opacity-0 cursor-pointer z-20"
                    />
                    <div className="border-2 border-dashed border-white/10 rounded-2xl p-10 flex flex-col items-center justify-center gap-4 transition-all group-hover:border-purple-500/50 group-hover:bg-white/5">
                        <div className="p-4 rounded-full bg-white/5 text-purple-400 group-hover:scale-110 transition-transform">
                            <Upload size={32} />
                        </div>
                        <div className="text-center">
                            <p className="font-medium text-lg">Drop your MP3 here</p>
                            <p className="text-sm text-white/40">or click to browse</p>
                        </div>
                    </div>
                </div>
            ) : (
                <div className="flex flex-col gap-6">
                    {/* File Info */}
                    <div className="flex items-center justify-between bg-white/5 p-4 rounded-xl border border-white/5">
                        <div className="flex items-center gap-3 overflow-hidden">
                            <div className="p-2 bg-purple-500/20 rounded-lg text-purple-400">
                                <Music size={20} />
                            </div>
                            <div className="min-w-0">
                                <p className="font-medium truncate">{file.name}</p>
                                <p className="text-xs text-white/40">{(file.size / 1024 / 1024).toFixed(2)} MB</p>
                            </div>
                        </div>
                        <button 
                            onClick={() => {
                                setFile(null); 
                                setIsPlaying(false);
                                Tone.Transport.stop();
                            }}
                            className="p-2 hover:bg-white/10 rounded-lg transition-colors text-white/60 hover:text-white"
                        >
                            <RefreshCw size={18} />
                        </button>
                    </div>

                    {/* Controls */}
                    <div className="space-y-6">
                        {/* Pitch Control */}
                        <div className="space-y-2">
                           <div className="flex justify-between items-center text-sm font-medium">
                               <span className="text-white/60">Pitch Shift</span>
                               <span className={cn("px-2 py-0.5 rounded text-xs", pitch > 0 ? "bg-green-500/20 text-green-400" : pitch < 0 ? "bg-red-500/20 text-red-400" : "bg-white/10 text-white/60")}>
                                   {pitch > 0 ? '+' : ''}{pitch} Semitones
                               </span>
                           </div>
                           <input 
                                type="range" 
                                min="-12" 
                                max="12" 
                                step="1" 
                                value={pitch} 
                                onChange={(e) => setPitch(Number(e.target.value))}
                                className="w-full h-2 bg-white/10 rounded-lg appearance-none cursor-pointer accent-purple-500"
                           />
                           <div className="flex justify-between text-xs text-white/30 px-1">
                               <span>-12</span>
                               <span>0</span>
                               <span>+12</span>
                           </div>
                        </div>

                         {/* Volume Control */}
                         <div className="space-y-2">
                           <div className="flex justify-between text-sm text-white/60">
                               <Volume2 size={16} />
                               <span>{Math.round((volume + 20) / 20 * 100)}%</span>
                           </div>
                           <input 
                                type="range" 
                                min="-20" 
                                max="0" 
                                step="0.5" 
                                value={volume} 
                                onChange={(e) => setVolume(Number(e.target.value))}
                                className="w-full h-1 bg-white/20 rounded-full appearance-none cursor-pointer [&::-webkit-slider-thumb]:w-3 [&::-webkit-slider-thumb]:h-3"
                           />
                        </div>
                    </div>

                    {/* Player UI */}
                    <div className="flex items-center gap-4">
                        <button 
                            onClick={togglePlay}
                            disabled={!isReady}
                            className="w-14 h-14 flex items-center justify-center rounded-full bg-white text-black hover:scale-105 transition-all shadow-[0_0_20px_rgba(255,255,255,0.3)] disabled:opacity-50 disabled:cursor-not-allowed"
                        >
                            {isPlaying ? <Pause fill="currentColor" /> : <Play fill="currentColor" className="ml-1" />}
                        </button>
                        
                        <div className="flex-1 space-y-1">
                             {/* Progress Bar */}
                             <input 
                                type="range" 
                                min="0" 
                                max={duration || 100} 
                                value={currentTime} 
                                onChange={handleSeek}
                                className="w-full h-1 bg-white/20 rounded-full appearance-none cursor-pointer [&::-webkit-slider-thumb]:w-3 [&::-webkit-slider-thumb]:h-3"
                             />
                             <div className="flex justify-between text-xs text-white/40">
                                 <span>{formatTime(currentTime)}</span>
                                 <span>{formatTime(duration)}</span>
                             </div>
                        </div>
                    </div>
                </div>
            )}
        </div>

        {/* Action Button */}
        {file && (
             <div className="mt-6 flex justify-center">
                 <button 
                    onClick={handleDownload}
                    disabled={isProcessing || !isReady}
                    className="flex items-center gap-2 px-6 py-3 bg-purple-600 hover:bg-purple-500 rounded-xl font-medium transition-all shadow-lg hover:shadow-purple-500/25 disabled:opacity-50 disabled:cursor-not-allowed"
                 >
                     {isProcessing ? (
                         <RefreshCw className="animate-spin" size={20} />
                     ) : (
                         <Download size={20} />
                     )}
                     {isProcessing ? 'Rendering...' : 'Download Transposed MP3'}
                 </button>
             </div>
        )}
      </div>
      <Footer />
      <VisitCounter />
    </div>
  );
}

function formatTime(seconds) {
    if (!seconds) return "0:00";
    const m = Math.floor(seconds / 60);
    const s = Math.floor(seconds % 60);
    return `${m}:${s < 10 ? '0' : ''}${s}`;
}
