import React, { useState, useEffect, useRef } from 'react';
import { Play, Pause, RotateCcw, Pill, Info, Microscope, Activity } from 'lucide-react';
import { LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer } from 'recharts';
import { motion, AnimatePresence } from 'framer-motion';

// --- Constants & Config ---
const PETRI_RADIUS = 150;
const MAX_POPULATION = 60;
const INITIAL_POPULATION = 10;
const TICK_RATE = 50; // ms
const REPRODUCTION_CHANCE = 0.015; // Adjusted for manageable pace
const MUTATION_RATE = 0.05; // 5% chance to mutate from S -> R
const ANTIBIOTIC_KILL_RATE = 0.95; // Highly effective against Susceptible

// --- Helper: Generate Bacteria ---
const generateBacterium = (type, x, y) => {
  const angle = Math.random() * Math.PI * 2;
  const radius = Math.random() * (PETRI_RADIUS - 30); 
  return {
    id: Math.random().toString(36).substr(2, 9),
    type: type, // 'susceptible' (blue) or 'resistant' (red)
    x: x ?? Math.cos(angle) * radius,
    y: y ?? Math.sin(angle) * radius,
    vx: (Math.random() - 0.5) * 1.2,
    vy: (Math.random() - 0.5) * 1.2,
    scale: 0, // for entrance animation
  };
};

// --- Helper: Custom Interval Hook ---
function useInterval(callback, delay) {
  const savedCallback = useRef();
  useEffect(() => { savedCallback.current = callback; }, [callback]);
  useEffect(() => {
    if (delay !== null) {
      const id = setInterval(() => savedCallback.current(), delay);
      return () => clearInterval(id);
    }
  }, [delay]);
}




const Footer = () => (
  <footer className="mt-12 text-center text-white/40 text-sm z-10 p-4">
      <p className="italic mb-1">But God made the earth by his power; he founded the world by his wisdom and stretched out the heavens by his understanding. Jeremiah 10:12</p>
      <p className="text-xs mb-1 mt-2">「耶和華用能力創造大地，用智慧建立世界，用聰明鋪張穹蒼。」 耶利米書 10:12</p>
      <p className="text-xs mt-2 pt-2 border-t border-white/10">@ 2025 Generated by Gemini 3.0 Prepared by SF Lau</p>
  </footer>
);

const VisitCounter = () => {
  const [visits, setVisits] = React.useState(0);
  React.useEffect(() => {
    const key = window.location.pathname.replace(/\//g, '_') || 'home';
    fetch(`https://api.countapi.xyz/hit/keithsflau-profile/${key}`)
      .then(res => res.json())
      .then(data => setVisits(data.value))
      .catch(err => console.error(err));
  }, []);
  return (
    <div className="fixed bottom-2 right-2 text-[10px] text-white/20 pointer-events-none z-50">
      Visits: {visits}
    </div>
  );
};

export default function App() {
  // --- State ---
  const [bacteria, setBacteria] = useState([]);
  const [history, setHistory] = useState([]);
  const [time, setTime] = useState(0); 
  const [ticks, setTicks] = useState(0); 
  const [isRunning, setIsRunning] = useState(false);
  const [flash, setFlash] = useState(false);
  const [annotation, setAnnotation] = useState({ title: "Start", text: "Bacteria multiply by binary fission. Click 'Start Growth' to begin." });

  // --- Stats Derived State ---
  const countStats = {
    susceptible: bacteria.filter(b => b.type === 'susceptible').length,
    resistant: bacteria.filter(b => b.type === 'resistant').length,
    total: bacteria.length
  };

  // --- Initialization ---
  useEffect(() => {
    resetSimulation();
  }, []);

  const resetSimulation = () => {
    const initial = Array.from({ length: INITIAL_POPULATION }).map(() => generateBacterium('susceptible'));
    const initialHistory = [{ time: 0, susceptible: INITIAL_POPULATION, resistant: 0 }];
    
    setBacteria(initial);
    setHistory(initialHistory);
    setTime(0);
    setTicks(0);
    setIsRunning(false);
    setAnnotation({ title: "Introduction", text: "Population starts with Susceptible bacteria (Blue). They are vulnerable to antibiotics." });
  };

  // --- Simulation Loop ---
  useInterval(() => {
    if (!isRunning) return;

    setTicks(t => t + 1);
    
    setBacteria(currentBacteria => {
      // 1. Movement & Boundaries
      let nextBacteria = currentBacteria.map(b => {
        let nx = b.x + b.vx;
        let ny = b.y + b.vy;
        
        // Soft Boundary Check (Circle)
        const dist = Math.sqrt(nx * nx + ny * ny);
        let nvx = b.vx;
        let nvy = b.vy;

        if (dist >= PETRI_RADIUS - 8) {
          // Reflect against circle normal around collision point
          const nx_n = nx / dist;
          const ny_n = ny / dist;
          const dot = b.vx * nx_n + b.vy * ny_n;
          nvx = b.vx - 2 * dot * nx_n;
          nvy = b.vy - 2 * dot * ny_n;
          
          // Push back inside
          nx = nx_n * (PETRI_RADIUS - 9);
          ny = ny_n * (PETRI_RADIUS - 9);
        }

        return { ...b, x: nx, y: ny, vx: nvx, vy: nvy, scale: 1 };
      });

      // 2. Reproduction
      const newBacteria = [];
      // Only reproduce if we aren't at global max capacity
      if (nextBacteria.length < MAX_POPULATION) {
        nextBacteria.forEach(b => {
           // Logistic-ish: Probability decreases as population fills
           const crowdingFactor = 1 - (nextBacteria.length / MAX_POPULATION);
           const adjustedChance = REPRODUCTION_CHANCE * crowdingFactor;

           if (Math.random() < adjustedChance) {
             let newType = b.type;
             // Mutation: Susceptible parent can give birth to Resistant child
             if (b.type === 'susceptible' && Math.random() < MUTATION_RATE) {
               newType = 'resistant';
             }
             // Offset new bacterium slightly
             newBacteria.push(generateBacterium(newType, b.x + b.vx*2, b.y + b.vy*2));
           }
        });
      }
      
      // 3. Update Population
      let finalBacteria = [...nextBacteria, ...newBacteria];

      // 4. Overpopulation Death (Standard Natural Selection - Competition)
      if (finalBacteria.length > MAX_POPULATION) {
         // Random death due to overcrowding
         finalBacteria = finalBacteria.sort(() => 0.5 - Math.random()).slice(0, MAX_POPULATION);
      }

      return finalBacteria;
    });

    // Update History & Annotations every 1s (20 ticks)
    if (ticks % 20 === 0) {
      const newTime = ticks / 20;
      setTime(newTime);
      setHistory(h => {
        const newEntry = { 
            time: newTime, 
            susceptible: countStats.susceptible, 
            resistant: countStats.resistant 
        };
        // Keep history window manageable (last 60s)
        if (h.length > 60) return [...h.slice(1), newEntry];
        return [...h, newEntry];
      });
      updateEducationalContext(); 
    }

  }, TICK_RATE);

  // --- Educational Logic ---
  const updateEducationalContext = () => {
    const s = countStats.susceptible;
    const r = countStats.resistant;
    const total = countStats.total;

    if (total === 0) {
      setAnnotation({ title: "Extinction", text: "The antibiotic wiped out the population. No resistance genes were passed on." });
      setIsRunning(false);
      return;
    }
    
    if (r > 0 && r < total * 0.3) {
      setAnnotation({ title: "Variation", text: "Mutation has occurred! A resistant bacterium (Red) is born. Genetic variation exists." });
    } else if (r >= total * 0.3 && r < total * 0.8) {
      setAnnotation({ title: "Selection", text: "If antibiotics are present, resistant bacteria survive and reproduce, while blue ones die." });
    } else if (r >= total * 0.8) {
      setAnnotation({ title: "Evolution", text: "The population has evolved. The allele for resistance is now dominant." });
    } else if (total > MAX_POPULATION * 0.9 && r === 0) {
      setAnnotation({ title: "Competition", text: "Carrying capacity reached. Bacteria compete for resources." });
    }
  };

  const getResistanceFrequency = () => {
    if (countStats.total === 0) return "0.0";
    return ((countStats.resistant / countStats.total) * 100).toFixed(1);
  };

  // --- User Actions ---
  const applyAntibiotic = () => {
    setFlash(true);
    setTimeout(() => setFlash(false), 600);
    setBacteria(prev => prev.filter(b => {
      // Resistant bacteria survive (scale to 0 for exit animation logic if we had it, but filter removes)
      if (b.type === 'resistant') return true; 
      // Susceptible die
      return Math.random() > ANTIBIOTIC_KILL_RATE; 
    }));
    setAnnotation({ title: "Selection Pressure", text: "Antibiotic kills susceptible bacterial! Resistant ones survive to pass on their genes." });
  };

  return (
    <div className="min-h-screen bg-slate-900 text-slate-100 font-sans flex flex-col items-center py-8 selection:bg-teal-500 selection:text-white">
      
      {/* Header */}
      <header className="max-w-6xl w-full px-6 mb-8 flex flex-col md:flex-row justify-between items-center gap-4">
        <div>
          <h1 className="text-3xl font-bold bg-gradient-to-r from-teal-400 to-blue-500 bg-clip-text text-transparent flex items-center gap-3">
            <Microscope className="text-teal-400" size={32} />
            Antibiotic Resistance
          </h1>
          <p className="text-slate-400 text-sm mt-1">Natural Selection Simulator • HKDSE Biology</p>
        </div>
        <div className="flex items-center gap-4 text-sm font-medium bg-slate-800 py-2 px-4 rounded-full border border-slate-700">
           <span className="flex items-center gap-2"><div className="w-3 h-3 rounded-full bg-blue-500 shadow-[0_0_8px_rgba(59,130,246,0.8)]"></div> Susceptible</span>
           <span className="flex items-center gap-2"><div className="w-3 h-3 rounded-full bg-rose-500 shadow-[0_0_8px_rgba(244,63,94,0.8)]"></div> Resistant</span>
        </div>
      </header>

      {/* Main Grid */}
      <main className="grid grid-cols-1 lg:grid-cols-12 gap-6 max-w-7xl w-full px-4 flex-1">
        
        {/* Left: Petri Dish (Visuals) */}
        <section className="lg:col-span-5 flex flex-col gap-4">
          <div className="bg-slate-800/50 backdrop-blur-md border border-slate-700 rounded-3xl p-8 flex flex-col items-center justify-center relative shadow-2xl min-h-[400px]">
            {/* Petri Dish Container */}
            <div className="relative group cursor-crosshair">
              {/* Box Shadow & Rim */}
              <div 
                className="rounded-full border-[12px] border-white/10 bg-slate-900 overflow-hidden relative shadow-[inset_0_0_40px_rgba(0,0,0,0.5)]"
                style={{ width: PETRI_RADIUS * 2, height: PETRI_RADIUS * 2 }}
              >
                 {/* Internal Gradient Grid */}
                 <div className="absolute inset-0 opacity-20 bg-[radial-gradient(circle_at_center,_var(--tw-gradient-stops))] from-teal-900/40 via-transparent to-transparent pointer-events-none"></div>
                 
                 {/* Flash Effect */}
                 <AnimatePresence>
                   {flash && (
                     <motion.div 
                       initial={{ opacity: 0 }} 
                       animate={{ opacity: 0.4 }} 
                       exit={{ opacity: 0 }}
                       className="absolute inset-0 bg-rose-500 z-0 pointer-events-none mix-blend-overlay"
                     />
                   )}
                 </AnimatePresence>

                 {/* Bacteria */}
                 {bacteria.map(b => (
                    <motion.div
                      key={b.id}
                      initial={{ scale: 0 }}
                      animate={{ 
                        x: PETRI_RADIUS + b.x - 6,
                        y: PETRI_RADIUS + b.y - 6,
                        scale: 1 
                      }}
                      transition={{ duration: 0 }} // Instant for game loop fluidness, can turn on strict mode for smoothness but React render is fast enough
                      className={`absolute w-3 h-3 rounded-full shadow-sm z-10 ${
                        b.type === 'resistant' 
                          ? 'bg-rose-500 shadow-[0_0_12px_rgba(244,63,94,0.6)]' 
                          : 'bg-blue-500 shadow-[0_0_12px_rgba(59,130,246,0.6)]'
                      }`}
                    />
                 ))}
                 
                 {/* Reflection/Glass Effect */}
                 <div className="absolute inset-0 rounded-full bg-gradient-to-tr from-white/5 to-transparent pointer-events-none"></div>
              </div>
            </div>

            {/* Stats Under Dish */}
            <div className="grid grid-cols-3 gap-2 w-full mt-6">
              <div className="bg-slate-900/80 p-3 rounded-xl border border-slate-700 text-center">
                 <div className="text-2xl font-bold text-blue-400">{countStats.susceptible}</div>
                 <div className="text-[10px] text-slate-500 uppercase tracking-widest">Susceptible</div>
              </div>
              <div className="bg-slate-900/80 p-3 rounded-xl border border-slate-700 text-center">
                 <div className="text-2xl font-bold text-rose-400">{countStats.resistant}</div>
                 <div className="text-[10px] text-slate-500 uppercase tracking-widest">Resistant</div>
              </div>
              <div className="bg-slate-900/80 p-3 rounded-xl border border-slate-700 text-center">
                 <div className="text-2xl font-bold text-teal-400">{getResistanceFrequency()}%</div>
                 <div className="text-[10px] text-slate-500 uppercase tracking-widest">Freq. Allele</div>
              </div>
            </div>
          </div>
        </section>

        {/* Right: Controls & Data */}
        <section className="lg:col-span-7 flex flex-col gap-6">
          
          {/* Top Panel: Controls */}
          <div className="bg-slate-800 border border-slate-700 rounded-2xl p-6 shadow-lg flex flex-col md:flex-row gap-6 items-center justify-between">
             <div className="flex gap-4 w-full md:w-auto">
               <button 
                 onClick={() => setIsRunning(!isRunning)}
                 className={`flex-1 md:flex-none flex items-center justify-center gap-2 px-6 py-3 rounded-xl font-bold text-white transition-all shadow-lg active:scale-95 ${
                   isRunning 
                     ? 'bg-amber-500 hover:bg-amber-600 shadow-amber-500/20' 
                     : 'bg-teal-500 hover:bg-teal-600 shadow-teal-500/20'
                 }`}
               >
                 {isRunning ? <><Pause size={20} /> Pause</> : <><Play size={20} /> Start</>}
               </button>
               <button
                 onClick={resetSimulation}
                 className="px-4 py-3 rounded-xl bg-slate-700 text-slate-300 hover:bg-slate-600 hover:text-white transition-colors"
               >
                 <RotateCcw size={20} />
               </button>
             </div>

             <div className="w-full md:w-auto flex-1 md:max-w-xs">
                <button 
                  onClick={applyAntibiotic}
                  disabled={!isRunning}
                  className="w-full flex items-center justify-center gap-2 px-6 py-3 rounded-xl bg-rose-600 text-white font-bold text-lg shadow-lg shadow-rose-900/50 hover:bg-rose-500 hover:shadow-rose-600/40 active:bg-rose-700 disabled:opacity-50 disabled:cursor-not-allowed transition-all border border-rose-500"
                >
                  <Pill size={20} /> Take Dose
                </button>
                <div className="text-center mt-2 text-xs text-slate-500 font-medium">Kills Susceptible Bacteria</div>
             </div>
          </div>

          {/* Graph Panel */}
          <div className="bg-slate-800 border border-slate-700 rounded-2xl p-6 shadow-lg flex-1 min-h-[300px] flex flex-col">
            <h3 className="text-lg font-semibold text-slate-300 mb-4 flex items-center gap-2">
              <Activity size={18} className="text-teal-500"/> Population Growth
            </h3>
            <div className="flex-1 w-full min-h-[250px]">
              <ResponsiveContainer width="100%" height="100%">
                <LineChart data={history}>
                  <CartesianGrid strokeDasharray="3 3" stroke="#334155" vertical={false} />
                  <XAxis 
                    dataKey="time" 
                    stroke="#94a3b8"
                    tick={{fontSize: 12, fill: '#64748b'}}
                    tickLine={false}
                    axisLine={false}
                  />
                  <YAxis 
                    stroke="#94a3b8"
                    tick={{fontSize: 12, fill: '#64748b'}}
                    tickLine={false}
                    axisLine={false}
                  />
                  <Tooltip 
                    contentStyle={{ backgroundColor: '#1e293b', borderColor: '#334155', borderRadius: '12px', color:'#f1f5f9' }}
                    itemStyle={{ fontSize: '14px' }}
                  />
                  <Legend verticalAlign="top" height={36}/>
                  <Line 
                    type="monotone" 
                    dataKey="susceptible" 
                    stroke="#3b82f6" 
                    strokeWidth={3} 
                    dot={false}
                    activeDot={{ r: 6 }}
                    name="Susceptible"
                    animationDuration={500}
                  />
                  <Line 
                    type="monotone" 
                    dataKey="resistant" 
                    stroke="#f43f5e" 
                    strokeWidth={3} 
                    dot={false}
                    activeDot={{ r: 6 }}
                    name="Resistant"
                    animationDuration={500}
                  />
                </LineChart>
              </ResponsiveContainer>
            </div>
          </div>
        </section>

      </main>

      {/* Educational Annotation Footer */}
      <AnimatePresence mode="wait">
        <motion.div 
          key={annotation.title} // Re-animate on title change
          initial={{ y: 20, opacity: 0 }}
          animate={{ y: 0, opacity: 1 }}
          exit={{ y: -20, opacity: 0 }}
          transition={{ duration: 0.3 }}
          className="fixed bottom-6 max-w-3xl w-[90%] md:w-full bg-slate-800/90 backdrop-blur-lg border-l-4 border-teal-500 text-slate-100 p-5 rounded-r-xl shadow-2xl flex items-start gap-4 z-50"
        >
          <div className="bg-teal-500/20 p-2 rounded-lg text-teal-400">
             <Info size={24} />
          </div>
          <div>
            <h4 className="font-bold text-teal-400 text-sm uppercase mb-1 tracking-wider">{annotation.title}</h4>
            <p className="text-slate-300 text-sm md:text-base leading-relaxed">{annotation.text}</p>
          </div>
        </motion.div>
      </AnimatePresence>
      <Footer />
      <VisitCounter />
    </div>
  );
}
