import React, { useState } from 'react';
import Scene1_Pollination from './components/Scene1_Pollination';
import Scene2_Fertilization from './components/Scene2_Fertilization';
import Scene3_Matching from './components/Scene3_Matching';
import { Flower } from 'lucide-react';




const Footer = () => (
  <footer className="mt-12 text-center text-white/40 text-sm z-10 p-4">
      <p className="italic mb-1">But God made the earth by his power; he founded the world by his wisdom and stretched out the heavens by his understanding. Jeremiah 10:12</p>
      <p className="text-xs mb-1 mt-2">「耶和華用能力創造大地，用智慧建立世界，用聰明鋪張穹蒼。」 耶利米書 10:12</p>
      <p className="text-xs mt-2 pt-2 border-t border-white/10">@ 2025 Generated by Gemini 3.0 Prepared by SF Lau</p>
  </footer>
);

const VisitCounter = () => {
  const [visits, setVisits] = React.useState(0);
  React.useEffect(() => {
    const key = window.location.pathname.replace(/\//g, '_') || 'home';
    fetch(`https://api.countapi.xyz/hit/keithsflau-profile/${key}`)
      .then(res => res.json())
      .then(data => setVisits(data.value))
      .catch(err => console.error(err));
  }, []);
  return (
    <div className="fixed bottom-2 right-2 text-[10px] text-white/20 pointer-events-none z-50">
      Visits: {visits}
    </div>
  );
};

export default function App() {
  const [currentStep, setCurrentStep] = useState(1);

  const nextStep = () => {
    setCurrentStep(prev => Math.min(prev + 1, 3));
  };

  return (
    <div className="min-h-screen bg-slate-50 font-sans text-slate-900 flex flex-col">
      {/* Header */}
      <header className="bg-emerald-800 text-white p-4 shadow-lg sticky top-0 z-50">
        <div className="max-w-5xl mx-auto flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="bg-white/20 p-2 rounded-full">
               <Flower className="text-pink-300" size={24} />
            </div>
            <div>
                <h1 className="text-xl font-bold tracking-tight">Sexual Reproduction in Plants</h1>
                <p className="text-xs text-emerald-200">HKDSE Biology Simulation</p>
            </div>
          </div>
          <nav className="hidden md:flex gap-1">
              {[1, 2, 3].map(step => (
                  <button
                    key={step}
                    onClick={() => setCurrentStep(step)}
                    className={`px-4 py-1 rounded-full text-sm font-semibold transition-all ${
                        currentStep === step 
                        ? 'bg-white text-emerald-800 shadow' 
                        : 'text-emerald-200 hover:bg-emerald-700'
                    }`}
                  >
                      Step {step}
                  </button>
              ))}
          </nav>
        </div>
      </header>

      {/* Progress Bar (Mobile/Desktop) */}
      <div className="bg-white border-b border-slate-200">
          <div className="max-w-5xl mx-auto px-4 py-4">
              <div className="flex items-center justify-between relative">
                  {/* Line */}
                  <div className="absolute left-0 top-1/2 w-full h-1 bg-slate-100 -z-10"></div>
                  <div className="absolute left-0 top-1/2 h-1 bg-emerald-500 -z-10 transition-all duration-500" style={{ width: `${(currentStep - 1) * 50}%` }}></div>

                  {/* Steps */}
                  <div 
                    className={`flex flex-col items-center gap-2 cursor-pointer ${currentStep >= 1 ? 'opacity-100' : 'opacity-50'}`}
                    onClick={() => setCurrentStep(1)}
                  >
                      <div className={`w-10 h-10 rounded-full flex items-center justify-center font-bold border-4 transition-all ${currentStep >= 1 ? 'bg-emerald-600 border-white text-white shadow-md scale-110' : 'bg-slate-200 border-white text-slate-500'}`}>1</div>
                      <span className="text-xs font-bold hidden sm:block">Pollination</span>
                  </div>

                  <div 
                    className={`flex flex-col items-center gap-2 cursor-pointer ${currentStep >= 2 ? 'opacity-100' : 'opacity-50'}`}
                    onClick={() => setCurrentStep(2)}
                  >
                      <div className={`w-10 h-10 rounded-full flex items-center justify-center font-bold border-4 transition-all ${currentStep >= 2 ? 'bg-pink-600 border-white text-white shadow-md scale-110' : 'bg-slate-200 border-white text-slate-500'}`}>2</div>
                      <span className="text-xs font-bold hidden sm:block">Double Fertilization</span>
                  </div>

                  <div 
                    className={`flex flex-col items-center gap-2 cursor-pointer ${currentStep >= 3 ? 'opacity-100' : 'opacity-50'}`}
                    onClick={() => setCurrentStep(3)}
                  >
                      <div className={`w-10 h-10 rounded-full flex items-center justify-center font-bold border-4 transition-all ${currentStep >= 3 ? 'bg-indigo-600 border-white text-white shadow-md scale-110' : 'bg-slate-200 border-white text-slate-500'}`}>3</div>
                      <span className="text-xs font-bold hidden sm:block">Development</span>
                  </div>
              </div>
          </div>
      </div>

      {/* Main Content */}
      <main className="flex-1 max-w-5xl mx-auto w-full p-4 md:p-8">
        {currentStep === 1 && <Scene1_Pollination onNext={nextStep} />}
        {currentStep === 2 && <Scene2_Fertilization onNext={nextStep} />}
        {currentStep === 3 && <Scene3_Matching />}
      </main>

      {/* Footer */}
      <footer className="bg-slate-800 text-slate-400 py-6 text-center text-sm">
        <p>© 2025 HKDSE Biology | Educational Simulation</p>
        <p className="mt-1">Built with React + Tailwind CSS</p>
      </footer>
      <Footer />
      <VisitCounter />
    </div>
  );
}
