<template>
  <div class="min-h-screen bg-gray-900 text-white p-4 md:p-8">
    <header class="max-w-7xl mx-auto mb-8 flex items-center justify-between">
      <div>
        <h1 class="text-3xl md:text-4xl font-extrabold text-transparent bg-clip-text bg-gradient-to-r from-blue-400 to-green-400">
          The Cell Cycle & Mitosis
        </h1>
        <p class="text-gray-400 mt-2">Interactive Visualizer for HKDSE Biology</p>
      </div>
      <!-- Progress Bar -->
      <div class="hidden md:block w-1/3">
         <div class="w-full bg-gray-700 rounded-full h-2.5">
            <div class="bg-blue-600 h-2.5 rounded-full transition-all duration-500" :style="{ width: (store.progress * 100) + '%' }"></div>
         </div>
      </div>
    </header>

    <main class="max-w-7xl mx-auto grid grid-cols-1 lg:grid-cols-3 gap-8">
      <!-- Main Visualizer Area (2/3 width) -->
      <div class="lg:col-span-2 space-y-6">
        <CellVisualizer />
        <DnaGraph />
      </div>

      <!-- Sidebar Area (1/3 width) -->
      <div class="lg:col-span-1">
        <Dashboard />
      </div>
    </main>

    <footer class="mt-12 text-center text-white/40 text-sm z-10 p-4">
      <p class="italic mb-1">But God made the earth by his power; he founded the world by his wisdom and stretched out the heavens by his understanding. Jeremiah 10:12</p>
      <p class="text-xs mb-1 mt-2">「耶和華用能力創造大地，用智慧建立世界，用聰明鋪張穹蒼。」 耶利米書 10:12</p>
      <p class="text-xs mt-2 pt-2 border-t border-white/10">@ 2025 Generated by Gemini 3.0 Prepared by SF Lau</p>
    </footer>
    <div class="fixed bottom-2 right-2 text-[10px] text-white/20 pointer-events-none z-50">
      Visits: {{ visits }}
    </div>
  </div>
</template>

<script setup>
import CellVisualizer from './components/CellVisualizer.vue'
import Dashboard from './components/Dashboard.vue'
import DnaGraph from './components/DnaGraph.vue'
import { useMitosisStore } from './stores/mitosis'
import { ref, onMounted } from 'vue'

const store = useMitosisStore()
const visits = ref(0) // Default 0

onMounted(() => {
    const key = window.location.pathname.replace(/\//g, '_') || 'home';
    fetch(`https://api.countapi.xyz/hit/keithsflau-profile/${key}`)
      .then(res => res.json())
      .then(data => visits.value = data.value)
      .catch(err => console.error(err));
});
</script>

<style>
/* Global scrollbar styling */
::-webkit-scrollbar {
  width: 8px;
}
::-webkit-scrollbar-track {
  background: #1f2937; 
}
::-webkit-scrollbar-thumb {
  background: #4b5563; 
  border-radius: 4px;
}
::-webkit-scrollbar-thumb:hover {
  background: #6b7280; 
}
</style>
