
import React, { useState } from 'react';
import { motion } from 'framer-motion';
import PunnettModule from './components/PunnettModule';
import PedigreeModule from './components/PedigreeModule';
import { Dna, Grid3X3, GitFork } from 'lucide-react';
import clsx from 'clsx';

function App() {
  const [activeTab, setActiveTab] = useState('punnett');

  return (
    <div className="min-h-screen bg-slate-100 font-sans text-slate-800">
      {/* Header */}
      <header className="bg-white shadow-sm border-b border-slate-200 sticky top-0 z-10">
        <div className="max-w-6xl mx-auto px-4 h-16 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <div className="bg-scientific-600 p-2 rounded-lg text-white">
              <Dna className="w-6 h-6" />
            </div>
            <h1 className="text-xl md:text-2xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-scientific-700 to-scientific-500">
              HKDSE Genetics Master
            </h1>
          </div>
          <div className="text-xs md:text-sm text-slate-500 font-medium hidden md:block">
            Mendelian & Pedigree Analysis
          </div>
        </div>
      </header>

      {/* Main Content */}
      <main className="max-w-6xl mx-auto px-4 py-8">

        {/* Navigation Tabs */}
        <div className="flex gap-4 mb-8 overflow-x-auto pb-2">
          <button
            onClick={() => setActiveTab('punnett')}
            className={clsx(
              "flex items-center gap-2 px-6 py-3 rounded-xl font-bold transition-all shadow-sm border whitespace-nowrap",
              activeTab === 'punnett'
                ? "bg-scientific-600 text-white border-scientific-700 ring-2 ring-scientific-200"
                : "bg-white text-slate-600 border-slate-200 hover:bg-slate-50"
            )}
          >
            <Grid3X3 className="w-5 h-5" />
            Punnett Calculator
          </button>
          <button
            onClick={() => setActiveTab('pedigree')}
            className={clsx(
              "flex items-center gap-2 px-6 py-3 rounded-xl font-bold transition-all shadow-sm border whitespace-nowrap",
              activeTab === 'pedigree'
                ? "bg-scientific-600 text-white border-scientific-700 ring-2 ring-scientific-200"
                : "bg-white text-slate-600 border-slate-200 hover:bg-slate-50"
            )}
          >
            <GitFork className="w-5 h-5" />
            Pedigree Logic
          </button>
        </div>

        {/* View Container */}
        <div className="transition-all duration-300">
          {activeTab === 'punnett' ? (
            <motion.div
              key="punnett"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.4 }}
            >
              <PunnettModule />
            </motion.div>
          ) : (
            <motion.div
              key="pedigree"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.4 }}
            >
              <PedigreeModule />
            </motion.div>
          )}
        </div>

        {/* Footer info */}
        <div className="mt-12 text-center text-slate-400 text-sm">
          <p>© 2025 HKDSE Biology Tools. Designed for educational use.</p>
        </div>
      </main></div></div>
  );
}



export default App;

const Footer = () => (
  <footer className="mt-12 text-center text-white/40 text-sm z-10 p-4">
      <p className="italic mb-1">But God made the earth by his power; he founded the world by his wisdom and stretched out the heavens by his understanding. Jeremiah 10:12</p>
      <p className="text-xs mb-1 mt-2">「耶和華用能力創造大地，用智慧建立世界，用聰明鋪張穹蒼。」 耶利米書 10:12</p>
      <p className="text-xs mt-2 pt-2 border-t border-white/10">@ 2025 Generated by Gemini 3.0 Prepared by SF Lau</p>
  </footer>
);

const VisitCounter = () => {
  const [visits, setVisits] = React.useState(0);
  React.useEffect(() => {
    const key = window.location.pathname.replace(/\//g, '_') || 'home';
    fetch(`https://api.countapi.xyz/hit/keithsflau-profile/${key}`)
      .then(res => res.json())
      .then(data => setVisits(data.value))
      .catch(err => console.error(err));
  }, []);
  return (
    <div className="fixed bottom-2 right-2 text-[10px] text-white/20 pointer-events-none z-50">
      Visits: {visits}
    
      <Footer />
      <VisitCounter />
    </div>
  );
};

export default App;
