/** HKDSE Geography E1 · Dynamic Earth — curriculum alignment (CDC C&A Guide) */
window.DYNAMIC_EARTH = {
  elective: "E1",
  title_zh: "動態地球：香港的塑造",
  title_en: "Dynamic Earth: The Building of Hong Kong",
  source: "教育局《地理課程及評估指引》（中四至中六）選修部分 E1；必修 C1 機遇與風險（板塊構造）",
  topics: [
    {
      id: "earth_system",
      num: "01",
      title_zh: "地球系統與內部結構",
      title_en: "Earth System & Internal Structure",
      guiding: ["我們應如何將地球視為一個系統？", "地球的整體結構是怎樣的？"],
      concepts: ["地球系統", "地殼", "地幔", "地核", "地殼運動"],
      hours: "~6",
    },
    {
      id: "plate_tectonics",
      num: "02",
      title_zh: "板塊構造",
      title_en: "Plate Tectonics",
      guiding: ["主要板塊及板塊邊界在哪裡？", "板塊運動如何形成地貌？"],
      concepts: ["板塊構造論", "張裂／消亡／保守邊界", "環太平洋火環", "熱點"],
      hours: "~6",
      links: "必修 C1",
    },
    {
      id: "rock_cycle",
      num: "03",
      title_zh: "岩石循環",
      title_en: "Rock Cycle",
      guiding: ["岩石是如何形成的？"],
      concepts: ["火成岩", "沉積岩", "變質岩", "火山作用", "沉積作用", "變質作用"],
      hours: "~4",
    },
    {
      id: "hk_geology",
      num: "04",
      title_zh: "香港地質與地貌",
      title_en: "HK Geology & Geomorphology",
      guiding: ["香港的一般地貌與地質是怎樣的？", "主要岩石類型如何分布？"],
      concepts: ["花崗岩", "火山岩", "沉積岩", "褶曲", "斷層", "空間分布"],
      hours: "~6",
    },
    {
      id: "landform_processes",
      num: "05",
      title_zh: "塑造香港地貌的營力",
      title_en: "Processes Shaping HK",
      guiding: ["內營力與外營力如何塑造香港？"],
      concepts: ["褶皺", "斷層", "火山作用", "風化", "侵蝕", "塊體運動", "城市化影響"],
      hours: "~4",
    },
    {
      id: "tectonic_hazards",
      num: "06",
      title_zh: "構造災害",
      title_en: "Tectonic Hazards",
      guiding: ["板塊運動如何引致地震、火山及海嘯？", "為何有些震帶遠離板塊邊界？"],
      concepts: ["地震", "火山爆發", "海嘯", "里氏規模", "震源／震央", "熱點", "監測與減災"],
      hours: "~6",
      links: "必修 C1",
    },
    {
      id: "geo_management",
      num: "07",
      title_zh: "地質資源與災害管理",
      title_en: "Resources & Hazard Management",
      guiding: ["人們如何管理香港的地質資源與地質災害？"],
      concepts: ["填海物料", "山泥傾瀉", "斜坡鞏固", "深灣山泥傾瀉", "人地關係"],
      hours: "~6",
      cases: ["香港國際機場填海", "深灣（Sham Wan）山泥傾瀉"],
    },
  ],
  hkRocks: [
    { name: "花崗岩", en: "Granite", pct: "~50%", age: "侏羅紀至白堊紀", areas: "新界北部、大嶼山、南丫島等", color: "#c4a882" },
    { name: "火山岩", en: "Volcanic", pct: "~15%", age: "白堊紀末", areas: "西貢火山岩區、粮船湾等", color: "#8b5a3c" },
    { name: "沉積岩", en: "Sedimentary", pct: "~35%", age: "泥盆紀至第三紀", areas: "赤柱、北角、元朗部分", color: "#7a9e6a" },
  ],
  boundaries: [
    { type: "divergent", zh: "張裂邊界", landforms: "中大西洋海嶺、東非大裂谷、紅海", motion: "板塊互相分離", color: "#4ade80" },
    { type: "convergent", zh: "消亡邊界", landforms: "喜馬拉雅山、馬里亞納海溝、日本火山弧", motion: "板塊互相碰撞／俯衝", color: "#f97316" },
    { type: "conservative", zh: "保守邊界", landforms: "聖安德烈亞斯斷層、死海斷層", motion: "板塊水平擦過", color: "#38bdf8" },
  ],
};
