import React, { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { ChevronRight, ChevronLeft, RefreshCw, Shuffle, Scissors, Info, Microscope, Split } from 'lucide-react';

const Footer = () => (
  <footer className="mt-12 text-center text-white/40 text-sm z-10 p-4">
      <p className="italic mb-1">But God made the earth by his power; he founded the world by his wisdom and stretched out the heavens by his understanding. Jeremiah 10:12</p>
      <p className="text-xs mb-1 mt-2">「耶和華用能力創造大地，用智慧建立世界，用聰明鋪張穹蒼。」 耶利米書 10:12</p>
      <p className="text-xs mt-2 pt-2 border-t border-white/10">@ 2025 Generated by Gemini 3.0 Prepared by SF Lau</p>
  </footer>
);

const VisitCounter = () => {
  const [visits, setVisits] = useState(0);
  useEffect(() => {
    const key = window.location.pathname.replace(/\//g, '_') || 'home';
    fetch(`https://api.countapi.xyz/hit/keithsflau-profile/${key}`)
      .then(res => res.json())
      .then(data => setVisits(data.value))
      .catch(err => console.error(err));
  }, []);
  return (
    <div className="fixed bottom-2 right-2 text-[10px] text-white/20 pointer-events-none z-50">
      Visits: {visits}
    </div>
  );
};

// --- Constants & Data ---

const STEPS = [
  { id: 'intro', title: 'Start: Interphase', description: 'Cell prepares for division. DNA has replicated. We start with 2 sets of Homologous Chromosomes (2n = 4).' },
  { id: 'prophase1', title: 'Prophase I', description: 'Homologous chromosomes pair up (Synapsis) to form Bivalents. Crossing over can occur here.' },
  { id: 'metaphase1', title: 'Metaphase I', description: 'Homologous pairs align at the equator. Independent Assortment determines their orientation.' },
  { id: 'anaphase1', title: 'Anaphase I', description: 'Homologous chromosomes separate to opposite poles. Ploidy reduces from 2n to n.' },
  { id: 'telophase1', title: 'Telophase I & Cytokinesis', description: 'Two haploid daughter cells are formed. Chromosomes are still replicated (sister chromatids).' },
  { id: 'metaphase2', title: 'Metaphase II', description: 'Chromosomes align singly at the equator in both cells.' },
  { id: 'anaphase2', title: 'Anaphase II', description: 'Centromeres split. Sister chromatids separate and move to opposite poles.' },
  { id: 'result', title: 'Result: 4 Gametes', description: 'Four genetically unique haploid daughter cells (n=2).' },
  { id: 'fertilization', title: 'Fertilization', description: 'Select a sperm to fertilize the egg. This restores the diploid number (2n).' },
];

// Chromosome configurations
// We have 2 Pairs. Pair 1 (Long), Pair 2 (Short).
// Each Pair has a Paternal (Blue) and Maternal (Red) chromosome.
// Each Chromosome has 2 Chromatids (Left, Right).
// Each Chromatid has Top and Bottom segments (for Crossover).

const INITIAL_DNA_STATE = {
  // Pair 1 (Long)
  p1_pat: { color: 'blue', left: {t:'b', b:'b'}, right: {t:'b', b:'b'} }, // Paternal
  p1_mat: { color: 'red',  left: {t:'r', b:'r'}, right: {t:'r', b:'r'} }, // Maternal
  // Pair 2 (Short)
  p2_pat: { color: 'blue', left: {t:'b', b:'b'}, right: {t:'b', b:'b'} },
  p2_mat: { color: 'red',  left: {t:'r', b:'r'}, right: {t:'r', b:'r'} },
};

export default function App() {
  const [currentStepIndex, setCurrentStepIndex] = useState(0);
  const [dnaState, setDnaState] = useState(JSON.parse(JSON.stringify(INITIAL_DNA_STATE)));
  const [alignment, setAlignment] = useState({ p1: 0, p2: 0 }); // 0: Pat-Mat, 1: Mat-Pat
  const [crossoverDone, setCrossoverDone] = useState(false);
  const [selectedGameteIndex, setSelectedGameteIndex] = useState(null);
  
  const step = STEPS[currentStepIndex];

  // Reset
  const resetSimulation = () => {
    setCurrentStepIndex(0);
    setDnaState(JSON.parse(JSON.stringify(INITIAL_DNA_STATE)));
    setAlignment({ p1: 0, p2: 0 });
    setCrossoverDone(false);
    setSelectedGameteIndex(null);
  };

  // Handlers
  const handleNext = () => {
    if (currentStepIndex < STEPS.length - 1) setCurrentStepIndex(prev => prev + 1);
  };
  
  const handlePrev = () => {
    if (currentStepIndex > 0) setCurrentStepIndex(prev => prev - 1);
  };

  const handleCrossover = () => {
    if (crossoverDone || step.id !== 'prophase1') return;
    
    // Swap bottom segments of inner chromatids of Pair 1 (Pat Right <-> Mat Left)
    setDnaState(prev => ({
      ...prev,
      p1_pat: { ...prev.p1_pat, right: { ...prev.p1_pat.right, b: 'r' } },
      p1_mat: { ...prev.p1_mat, left:  { ...prev.p1_mat.left,  b: 'b' } },
    }));
    setCrossoverDone(true);
  };

  const handleShuffle = () => {
    setAlignment({
      p1: Math.random() > 0.5 ? 1 : 0,
      p2: Math.random() > 0.5 ? 1 : 0,
    });
  };

  // --- Rendering Helpers ---

  // Helper to get color class
  const getTailwindColor = (code) => code === 'b' ? 'bg-blue-500' : 'bg-red-500';
  const getBorderColor = (code) => code === 'b' ? 'border-blue-600' : 'border-red-600';

  // Chromosome Component
  // Props: full state object of the chromosome, size ('long'|'short'), vertical (bool)
  const Chromosome = ({ data, size, id }) => {
    const h = size === 'long' ? 'h-32' : 'h-20';
    const w = 'w-4';
    
    return (
      <div className="relative flex items-center justify-center mx-1 transition-transform duration-500">
         {/* Centromere */}
         <div className="absolute z-10 w-4 h-4 rounded-full bg-slate-800 border-2 border-white shadow-sm"></div>

         {/* Left Chromatid */}
         <div className={`flex flex-col ${w} ${h} -rotate-12 origin-center transform translate-x-1`}>
            <div className={`flex-1 w-full rounded-t-full ${getTailwindColor(data.left.t)} transition-colors duration-500`}></div>
            <div className={`flex-1 w-full rounded-b-full ${getTailwindColor(data.left.b)} transition-colors duration-500`}></div>
         </div>
         
         {/* Right Chromatid */}
         <div className={`flex flex-col ${w} ${h} rotate-12 origin-center transform -translate-x-1`}>
            <div className={`flex-1 w-full rounded-t-full ${getTailwindColor(data.right.t)} transition-colors duration-500`}></div>
            <div className={`flex-1 w-full rounded-b-full ${getTailwindColor(data.right.b)} transition-colors duration-500`}></div>
         </div>
      </div>
    );
  };

  // Single Chromatid Component (for Meiosis II / Gametes)
  const Chromatid = ({ data, size }) => {
      const h = size === 'long' ? 'h-32' : 'h-20';
      return (
          <div className={`flex flex-col w-4 ${h} relative shadow-md`}>
              {/* Centromere half */}
              <div className="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 w-3 h-3 rounded-full bg-slate-800 z-10"></div>
              <div className={`flex-1 w-full rounded-t-full ${getTailwindColor(data.t)}`}></div>
              <div className={`flex-1 w-full rounded-b-full ${getTailwindColor(data.b)}`}></div>
          </div>
      )
  }


  // --- Position Logic based on Step ---
  
  // This function returns the visual layout for the current step
  const renderVisuals = () => {
    const s = step.id;

    // determine positions based on alignment state
    // alignment 0: Pat Left, Mat Right. 1: Mat Left, Pat Right.
    
    const p1_L = alignment.p1 === 0 ? dnaState.p1_pat : dnaState.p1_mat;
    const p1_R = alignment.p1 === 0 ? dnaState.p1_mat : dnaState.p1_pat;
    const p2_L = alignment.p2 === 0 ? dnaState.p2_pat : dnaState.p2_mat;
    const p2_R = alignment.p2 === 0 ? dnaState.p2_mat : dnaState.p2_pat;

    // Wrapper for a bivalent pair
    const Bivalent = ({ left, right, size, interactable }) => (
      <div className="flex items-center justify-center gap-1 p-2 bg-white/10 rounded-xl backdrop-blur-sm border border-white/20">
         <Chromosome data={left} size={size} />
         <Chromosome data={right} size={size} />
         {interactable && !crossoverDone && (
             <motion.button 
                whileHover={{ scale: 1.1 }}
                whileTap={{ scale: 0.9 }}
                onClick={handleCrossover}
                className="absolute text-yellow-300 bg-black/50 rounded-full p-1 cursor-pointer animate-pulse"
                style={{ top: '60%' }}
             >
                 <Scissors size={20} />
             </motion.button>
         )}
         {interactable && crossoverDone && (
           <div className="absolute text-green-400 font-bold text-xs top-[60%] bg-black/60 px-2 py-1 rounded">Swapped!</div>
         )}
      </div>
    );

    switch(s) {
      case 'intro':
        return (
          <div className="flex flex-col items-center justify-center gap-8 h-full">
             <div className="text-white/60 text-lg mb-4">Nucleus (2n = 4)</div>
             <div className="relative w-96 h-96 rounded-full border-4 border-white/30 bg-slate-900/50 flex flex-wrap items-center justify-center gap-8 shadow-inner overflow-hidden">
                {/* Randomly floating */}
                <motion.div layoutId="p1p" className="absolute top-10 left-20"><Chromosome data={dnaState.p1_pat} size="long"/></motion.div>
                <motion.div layoutId="p1m" className="absolute bottom-10 right-20"><Chromosome data={dnaState.p1_mat} size="long"/></motion.div>
                <motion.div layoutId="p2p" className="absolute top-20 right-24"><Chromosome data={dnaState.p2_pat} size="short"/></motion.div>
                <motion.div layoutId="p2m" className="absolute bottom-24 left-16"><Chromosome data={dnaState.p2_mat} size="short"/></motion.div>
             </div>
          </div>
        );

      case 'prophase1':
        return (
            <div className="flex flex-col items-center justify-center gap-8 h-full">
            <div className="text-white/60 text-lg mb-4">Synapsis & Crossing Over</div>
            <div className="relative w-96 h-96 rounded-full border-4 border-dashed border-white/30 bg-slate-900/50 flex flex-col items-center justify-center gap-4 shadow-inner">
               {/* Pairs form bivalents */}
               {/* For crossing over visualization, strictly show Pat Left Mat Right for clarity initially, or follow alignment but force interaction view */}
               {/* We use default canonical view for crossover interaction: Pat-Mat */}
               <motion.div layoutId="bivalent1">
                 <Bivalent left={dnaState.p1_pat} right={dnaState.p1_mat} size="long" interactable={true} />
               </motion.div>
               <motion.div layoutId="bivalent2" className="flex gap-2">
                 <Chromosome data={dnaState.p2_pat} size="short"/>
                 <Chromosome data={dnaState.p2_mat} size="short"/>
               </motion.div>
            </div>
            <p className="text-sm text-blue-200 animate-pulse">Click the scissors to cross over!</p>
         </div>
        );

      case 'metaphase1':
          return (
            <div className="flex flex-col items-center justify-center gap-8 h-full">
            <div className="text-white/60 text-lg mb-4">Equatorial Alignment</div>
            {/* Cell with equator line */}
            <div className="relative w-96 h-96 rounded-full border-4 border-white/30 bg-slate-900/50 flex flex-col items-center justify-center shadow-inner">
                 <div className="absolute w-full h-0.5 bg-white/20 border-t border-dashed border-white/40"></div>
                 
                 <div className="z-10 flex flex-col gap-8">
                    <motion.div layout className="flex gap-8 items-center">
                        <Chromosome data={p1_L} size="long"/>
                        <Chromosome data={p1_R} size="long"/>
                    </motion.div>
                    <motion.div layout className="flex gap-8 items-center">
                        <Chromosome data={p2_L} size="short"/>
                        <Chromosome data={p2_R} size="short"/>
                    </motion.div>
                 </div>
            </div>
            <button onClick={handleShuffle} className="flex items-center gap-2 px-4 py-2 bg-indigo-600 rounded-full hover:bg-indigo-500 font-semibold shadow-lg transition-all active:scale-95">
                <Shuffle size={18}/> Shuffle Alignment
            </button>
         </div>
          );

      case 'anaphase1':
          return (
            <div className="flex flex-col items-center justify-center gap-8 h-full">
            <div className="text-white/60 text-lg mb-4">Homologous Separation</div>
            <div className="relative w-[500px] h-96 rounded-[100px] border-4 border-white/30 bg-slate-900/50 flex justify-between px-16 items-center shadow-inner overflow-hidden">
                 {/* Spindle Fibers */}
                 <svg className="absolute inset-0 w-full h-full opacity-20 pointer-events-none">
                     <path d="M20,192 Q250,192 480,192" stroke="white" strokeWidth="2" strokeDasharray="5,5"/>
                     <path d="M20,192 L480,100" stroke="white" strokeWidth="1" />
                     <path d="M20,192 L480,280" stroke="white" strokeWidth="1" />
                 </svg>

                 {/* Left Pole Group */}
                 <motion.div initial={{ x: 100 }} animate={{ x: 0 }} transition={{ duration: 2 }} className="flex flex-col gap-8">
                    <Chromosome data={p1_L} size="long"/>
                    <Chromosome data={p2_L} size="short"/>
                 </motion.div>

                 {/* Right Pole Group */}
                 <motion.div initial={{ x: -100 }} animate={{ x: 0 }} transition={{ duration: 2 }} className="flex flex-col gap-8">
                    <Chromosome data={p1_R} size="long"/>
                    <Chromosome data={p2_R} size="short"/>
                 </motion.div>
            </div>
         </div>
          );

      case 'telophase1':
          return (
            <div className="flex flex-col items-center justify-center gap-8 h-full">
                 <div className="text-white/60 text-lg mb-4">Ends of Meiosis I</div>
                 <div className="flex gap-8">
                     {/* Cell 1 */}
                     <div className="relative w-64 h-64 rounded-full border-4 border-white/30 bg-slate-900/50 flex flex-col items-center justify-center gap-4">
                        <div className="absolute top-2 left-1/2 -translate-x-1/2 text-xs text-white/50">Daughter Cell A (n=2)</div>
                        <Chromosome data={p1_L} size="long"/>
                        <Chromosome data={p2_L} size="short"/>
                     </div>
                     {/* Cell 2 */}
                     <div className="relative w-64 h-64 rounded-full border-4 border-white/30 bg-slate-900/50 flex flex-col items-center justify-center gap-4">
                        <div className="absolute top-2 left-1/2 -translate-x-1/2 text-xs text-white/50">Daughter Cell B (n=2)</div>
                        <Chromosome data={p1_R} size="long"/>
                        <Chromosome data={p2_R} size="short"/>
                     </div>
                 </div>
            </div>
          );
      
      case 'metaphase2':
          return (
            <div className="flex flex-col items-center justify-center gap-8 h-full">
            <div className="text-white/60 text-lg mb-4">Meiosis II: Alignment</div>
            <div className="flex gap-8">
                {/* Cell 1 */}
                <div className="relative w-64 h-64 rounded-full border-4 border-white/30 bg-slate-900/50 flex flex-col items-center justify-center gap-4">
                   <div className="absolute w-full h-0.5 bg-white/10 top-1/2"></div>
                   <Chromosome data={p1_L} size="long"/>
                   <Chromosome data={p2_L} size="short"/>
                </div>
                {/* Cell 2 */}
                <div className="relative w-64 h-64 rounded-full border-4 border-white/30 bg-slate-900/50 flex flex-col items-center justify-center gap-4">
                   <div className="absolute w-full h-0.5 bg-white/10 top-1/2"></div>
                   <Chromosome data={p1_R} size="long"/>
                   <Chromosome data={p2_R} size="short"/>
                </div>
            </div>
       </div>
          );
          
      case 'anaphase2':
            // Logic: Chromosomes split into chromatids.
            // Cell A splits p1_L and p2_L.
            // Cell B splits p1_R and p2_R.
            return (
                <div className="flex flex-col items-center justify-center gap-8 h-full">
                <div className="text-white/60 text-lg mb-4">Meiosis II: Sister Chromatids Separate</div>
                <div className="flex gap-12">
                    {/* Cell 1 Dividing */}
                    <div className="relative w-64 h-80 rounded-[50px] border-2 border-white/20 bg-slate-900/50 flex flex-col justify-between py-8 items-center">
                         {/* Top Pole */}
                         <div className="flex gap-2">
                             <Chromatid data={p1_L.left} size="long"/>
                             <Chromatid data={p2_L.left} size="short"/>
                         </div>
                         {/* Bottom Pole */}
                         <div className="flex gap-2">
                             <Chromatid data={p1_L.right} size="long"/>
                             <Chromatid data={p2_L.right} size="short"/>
                         </div>
                    </div>

                    {/* Cell 2 Dividing */}
                    <div className="relative w-64 h-80 rounded-[50px] border-2 border-white/20 bg-slate-900/50 flex flex-col justify-between py-8 items-center">
                         {/* Top Pole */}
                         <div className="flex gap-2">
                             <Chromatid data={p1_R.left} size="long"/>
                             <Chromatid data={p2_R.left} size="short"/>
                         </div>
                         {/* Bottom Pole */}
                         <div className="flex gap-2">
                             <Chromatid data={p1_R.right} size="long"/>
                             <Chromatid data={p2_R.right} size="short"/>
                         </div>
                    </div>
                </div>
           </div>
            )

      case 'result':
          // 4 Gametes
          const gametes = [
              { name: 'Gamete 1', c1: p1_L.left, c2: p2_L.left },
              { name: 'Gamete 2', c1: p1_L.right, c2: p2_L.right },
              { name: 'Gamete 3', c1: p1_R.left, c2: p2_R.left },
              { name: 'Gamete 4', c1: p1_R.right, c2: p2_R.right },
          ];

          return (
            <div className="flex flex-col items-center gap-8">
                <div className="text-2xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-blue-400 to-red-400">
                    Final Result: 4 Haploid Gametes
                </div>
                <div className="grid grid-cols-2 lg:grid-cols-4 gap-6">
                    {gametes.map((g, idx) => (
                        <motion.div 
                            key={idx}
                            initial={{ scale: 0, opacity: 0 }}
                            animate={{ scale: 1, opacity: 1 }}
                            transition={{ delay: idx * 0.2 }}
                            className="bg-white/5 backdrop-blur-md border border-white/10 p-6 rounded-2xl flex flex-col items-center gap-4 hover:bg-white/10 transition-colors"
                        >
                            <div className="text-sm font-bold text-white/70">{g.name}</div>
                            <div className="relative w-32 h-32 rounded-full border-2 border-white/20 flex items-center justify-center gap-2 bg-slate-800">
                                <Chromatid data={g.c1} size="long"/>
                                <Chromatid data={g.c2} size="short"/>
                            </div>
                            <div className="text-xs text-center text-slate-400">
                                Unique Combination due to <br/>
                                <span className="text-blue-300">{(crossoverDone && (idx === 0 || idx === 1 /* Simplify logic check */)) ? 'Crossing Over?' : ''}</span>
                                {' '} & {' '}
                                <span className="text-purple-300">Indep. Assortment</span>
                            </div>
                        </motion.div>
                    ))}
                </div>
                
                <div className="mt-8 p-6 bg-blue-900/20 border border-blue-500/30 rounded-xl max-w-3xl">
                    <h3 className="flex items-center gap-2 text-xl font-bold text-blue-300 mb-2">
                        <Microscope/> Analysis
                    </h3>
                    <ul className="space-y-2 text-blue-100/80">
                        <li className="flex items-start gap-2">
                            <Split size={16} className="mt-1 flex-shrink-0"/>
                            <span><strong>Variation Source 1 (Prophase I):</strong> {crossoverDone ? 'Crossing Over occurred, creating recombinant chromatids (mixed colors).' : 'No crossing over occurred.'}</span>
                        </li>
                        <li className="flex items-start gap-2">
                            <Shuffle size={16} className="mt-1 flex-shrink-0"/>
                            <span><strong>Variation Source 2 (Metaphase I):</strong> Independent Assortment shuffled the maternal/paternal chromosomes.</span>
                        </li>
                        <li className="flex items-start gap-2">
                            <Info size={16} className="mt-1 flex-shrink-0"/>
                            <span><strong>Outcome:</strong> 4 non-identical cells (gametes). In humans, this leads to 2^23 combinations + infinite crossover possibilities!</span>
                        </li>
                    </ul>
                </div>

                <button onClick={resetSimulation} className="flex items-center gap-2 px-6 py-3 bg-emerald-600 rounded-full hover:bg-emerald-500 font-bold shadow-lg transition-transform active:scale-95">
                    <RefreshCw/> Restart Simulation
                </button>
            </div>
          );

      case 'fertilization':
        // Gametes from previous step
        const availableGametes = [
            { name: 'Sperm 1', c1: p1_L.left, c2: p2_L.left },
            { name: 'Sperm 2', c1: p1_L.right, c2: p2_L.right },
            { name: 'Sperm 3', c1: p1_R.left, c2: p2_R.left },
            { name: 'Sperm 4', c1: p1_R.right, c2: p2_R.right },
        ];

        // Static Egg (Maternal Partner) - let's say she contributes Purple chromosomes
        const eggGamete = {
            c1: { t: 'p', b: 'p' }, // Purple (using a CSS class we'll need to handle or just red for now? Let's use Red but maybe distinct? Actually let's just make them Pink/Purple in styling or default to RED for female partner standard)
            // Let's stick to Red for Maternal but lighter/darker? 
            // Better: New color code 'm' (magenta/purple)
            c2: { t: 'p', b: 'p' } 
        };

        // Helper to override color for Egg if needed, or update getTailwindColor
        // simple hack: updated getTailwindColor to handle 'p'
        
        return (
            <div className="flex flex-col items-center gap-8 h-full">
                
                {selectedGameteIndex === null ? (
                    <>
                         <div className="text-xl text-blue-200 animate-pulse">Select a Sperm to Fertilize the Egg</div>
                         <div className="flex gap-4">
                             {/* Sperm Selection */}
                             <div className="grid grid-cols-2 gap-4">
                                {availableGametes.map((g, idx) => (
                                    <motion.button
                                        key={idx}
                                        whileHover={{ scale: 1.05 }}
                                        whileTap={{ scale: 0.95 }}
                                        onClick={() => setSelectedGameteIndex(idx)}
                                        className="bg-blue-900/40 border border-blue-500/30 p-4 rounded-xl flex flex-col items-center gap-2 cursor-pointer hover:bg-blue-800/50"
                                    >
                                        <div className="text-xs text-blue-300 font-bold">{g.name}</div>
                                        <div className="relative w-16 h-16 rounded-full border border-white/20 flex items-center justify-center gap-1 bg-slate-800">
                                            <Chromatid data={g.c1} size="long"/>
                                            <Chromatid data={g.c2} size="short"/>
                                            {/* Tail */}
                                            <div className="absolute -bottom-4 w-0.5 h-6 bg-white/50 animate-bounce"></div> 
                                        </div>
                                    </motion.button>
                                ))}
                             </div>

                             {/* The Egg */}
                             <div className="flex flex-col items-center justify-center p-8 bg-pink-900/20 border border-pink-500/30 rounded-full w-64 h-64 ml-12 relative shadow-[0_0_50px_rgba(236,72,153,0.2)]">
                                 <div className="text-pink-300 font-bold mb-2 absolute top-6">Egg (n=2)</div>
                                 <div className="flex gap-2">
                                     {/* Hardcoded 'p' for purple/pink? Or just use Red for now. Let's use 'r' but maybe add a filter? or just regular Red */}
                                     {/* Let's allow 'r' (Maternal) for now as simplicity. The partner is female. */}
                                     <Chromatid data={{t:'r', b:'r'}} size="long"/>
                                     <Chromatid data={{t:'r', b:'r'}} size="short"/>
                                 </div>
                             </div>
                         </div>
                    </>
                ) : (
                    <motion.div 
                        initial={{ opacity: 0, scale: 0.5 }}
                        animate={{ opacity: 1, scale: 1 }}
                        className="flex flex-col items-center gap-6"
                    >
                         <div className="text-3xl font-bold text-transparent bg-clip-text bg-gradient-to-r from-blue-400 via-purple-400 to-pink-400">
                             Zygote Formed (2n = 4)
                         </div>
                         
                         <div className="relative w-80 h-80 rounded-full border-4 border-white/40 bg-slate-900 shadow-[0_0_100px_rgba(255,255,255,0.1)] flex items-center justify-center gap-4 overflow-hidden">
                             {/* Sperm Chromosomes */}
                             <div className="flex gap-2 absolute top-1/4 left-1/4 transform -translate-x-1/2">
                                 <Chromatid data={availableGametes[selectedGameteIndex].c1} size="long"/>
                                 <Chromatid data={availableGametes[selectedGameteIndex].c2} size="short"/>
                             </div>

                             {/* Egg Chromosomes */}
                             <div className="flex gap-2 absolute bottom-1/4 right-1/4 transform translate-x-1/2">
                                 <Chromatid data={{t:'r', b:'r'}} size="long"/>
                                 <Chromatid data={{t:'r', b:'r'}} size="short"/>
                             </div>

                             {/* Sparkles */}
                             <motion.div 
                                animate={{ rotate: 360 }}
                                transition={{ duration: 10, repeat: Infinity, ease: "linear" }}
                                className="absolute inset-0 border-2 border-dashed border-white/10 rounded-full"
                             />
                         </div>

                         <div className="p-4 bg-purple-900/30 border border-purple-500/30 rounded-xl text-center max-w-lg">
                             <p className="text-purple-200">
                                 <strong>Genetic Variation Source #3:</strong> Random Fertilization.
                                 <br/>
                                 Any of the millions of sperm could have fertilized the egg, creating a unique individual.
                             </p>
                         </div>
                         
                         <button onClick={() => setSelectedGameteIndex(null)} className="text-sm text-slate-400 hover:text-white underline mt-2">
                             Try another sperm
                         </button>
                         
                         <button onClick={resetSimulation} className="mt-4 flex items-center gap-2 px-6 py-3 bg-emerald-600 rounded-full hover:bg-emerald-500 font-bold shadow-lg">
                             <RefreshCw/> Start New Meiosis
                         </button>
                    </motion.div>
                )}
            </div>
        );

      default: return null;
    }
  };

  // --- Main Layout ---

  return (
    <div className="min-h-screen bg-slate-950 text-white font-sans selection:bg-blue-500/30">
        {/* Navbar */}
        <nav className="fixed top-0 left-0 w-full p-4 bg-slate-900/80 backdrop-blur-md border-b border-white/10 z-50 flex justify-between items-center">
             <div className="flex items-center gap-3">
                 <div className="w-8 h-8 rounded bg-gradient-to-br from-blue-500 to-red-500 flex items-center justify-center font-bold text-sm shadow-lg">M</div>
                 <h1 className="text-xl font-bold tracking-tight">Meiosis Simulation</h1>
             </div>
             
             <div className="flex items-center gap-4 text-sm">
                 <div className="px-3 py-1 bg-white/5 rounded-full border border-white/10">
                     Step {currentStepIndex + 1} of {STEPS.length}
                 </div>
                 <div className="hidden md:flex gap-1">
                     {STEPS.map((s, i) => (
                         <div key={s.id} className={`w-2 h-2 rounded-full transition-all ${i === currentStepIndex ? 'bg-blue-400 w-6' : 'bg-slate-700'}`}/>
                     ))}
                 </div>
             </div>
        </nav>

        {/* Main Content Area */}
        <main className="pt-20 pb-24 h-screen flex flex-col">
            
            {/* Simulation Viewport */}
            <div className="flex-1 relative overflow-hidden flex items-center justify-center bg-gradient-to-b from-slate-900 to-slate-950">
                 {/* Background Elements */}
                 <div className="absolute inset-0 opacity-20 pointer-events-none bg-[radial-gradient(ellipse_at_center,_var(--tw-gradient-stops))] from-blue-900/20 via-slate-950 to-slate-950"></div>
                 
                 <AnimatePresence mode="wait">
                     <motion.div 
                        key={step.id}
                        initial={{ opacity: 0, scale: 0.95 }}
                        animate={{ opacity: 1, scale: 1 }}
                        exit={{ opacity: 0, scale: 1.05 }}
                        transition={{ duration: 0.5 }}
                        className="w-full h-full p-8 overflow-y-auto"
                     >
                         {renderVisuals()}
                         <Footer />
                     </motion.div>
                 </AnimatePresence>
            </div>

            {/* Bottom Controls */}
            <div className="fixed bottom-0 left-0 w-full p-6 bg-slate-900/90 backdrop-blur-xl border-t border-white/10 z-50">
                <div className="max-w-5xl mx-auto flex flex-col md:flex-row items-center justify-between gap-6">
                    <div className="flex-1">
                        <h2 className="text-xl font-bold text-blue-200 mb-1 flex items-center gap-2">
                           {step.title}
                           {step.id === 'prophase1' && <span className="text-xs bg-yellow-500/20 text-yellow-300 px-2 py-0.5 rounded border border-yellow-500/30">Action Required</span>}
                        </h2>
                        <p className="text-slate-400 text-sm leading-relaxed">{step.description}</p>
                    </div>

                    <div className="flex items-center gap-4">
                        <button 
                            onClick={handlePrev} 
                            disabled={currentStepIndex === 0}
                            className="p-3 rounded-full hover:bg-white/10 disabled:opacity-30 disabled:hover:bg-transparent transition-colors"
                        >
                            <ChevronLeft size={24}/>
                        </button>
                        
                        <button
                            onClick={handleNext}
                            disabled={currentStepIndex === STEPS.length - 1}
                            className="flex items-center gap-2 px-6 py-3 bg-blue-600 hover:bg-blue-500 rounded-full font-bold shadow-lg shadow-blue-900/20 transition-all active:scale-95 disabled:opacity-50 disabled:grayscale"
                        >
                            Next Step <ChevronRight size={18}/>
                        </button>
                    </div>
                </div>
            </div>
        </main>
        
        {/* Educational Tooltip/Overlay */}
        <div className="fixed top-24 right-6 max-w-xs z-40 hidden lg:block">
            <div className="bg-slate-800/80 backdrop-blur border border-white/10 p-4 rounded-xl shadow-xl">
                <h4 className="font-bold text-gray-300 text-sm mb-2 flex items-center gap-2">
                    <Info size={14}/> Key Concept
                </h4>
                <div className="text-xs text-gray-400 space-y-2">
                    <p><strong className="text-blue-300">Haploid (n):</strong> A cell containing only one set of chromosomes (like gametes).</p>
                    <div className="h-px bg-white/10"></div>
                    <p><strong className="text-red-300">Vs Mitosis:</strong> Mitosis separates sister chromatids immediately. Meiosis I separates homologous pairs first, ensuring genetic reduction.</p>
                </div>
            </div>
        </div>
        <VisitCounter />
    </div>
  );
}
